### ISSUE TITLE
'pip install mozcpy' failed 

### ISSUE THREAD

**Issue by ngocnp** [ikegami-yukino/mozcpy#2]
I got this error when installing mozcpy:

```
python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-vgfh7wgc/mozcpy_41adbd3297a04ce9bfde91c1db9c58d9/setup.py", line 41, in <module>
          open('CHANGES.rst', encoding='utf8').read()
        File "/home/ngocnp/anaconda3/envs/test/lib/python3.8/codecs.py", line 905, in open
          file = builtins.open(filename, mode, buffering)
      FileNotFoundError: [Errno 2] No such file or directory: 'CHANGES.rst'
```
Please add CHANGES.rst to package archive

**Comment by ikegami-yukino** [comment]
@ngocnp 
Thank you for the reporting 👍 
I fixed this problem!
Please try it again!
```
$ python3 -m pip install mozcpy
```
